### ISSUE TITLE
Tune the portal lights down

### ISSUE THREAD

**Issue by bergie** [c-base/ingress-table#1]
When the table is in the dimly-lit c-base main hall, the current portal lights are slightly too bright. We should tune them down a bit.

https://github.com/c-base/ingress-table/blob/master/components/StateToColor.coffee#L62 and https://github.com/c-base/ingress-table/blob/master/components/StateToColor.coffee#L83

**Comment by jonnor** [comment]
With live mode, we could have a slider for this in Flowhub/web-ui. 
Alternative/complimentary would be to have a physical pot-meter to adjust

**Comment by ij0n** [comment]
I think it would not be very hard to attach a lightsensor to the arduino.

**Comment by bergie** [comment]
@ij0n it wouldn't, but where would be place the sensor so that it won't be blinded by beer bottles, laptops, and such?

**Comment by cannonerd** [comment]
I want a physical knob! "I shall turn this table up to eleven!"

**Comment by ij0n** [comment]
@bergie good question! we could for example add more then one. a good position is in my opinion through the maplayer-supportboards at the sides. maybe one at each corner? so we could compensate.

most people dont put stuff like beerbottles and laptops right at the corners because of the danger of falling down.

**Comment by bergie** [comment]
Main hall is way less dimly lit now, so table doesn't look that bright
